# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Applio-Example' do
  # Comment the next line if you don't want to use dynamic frameworks

pod 'Applio', :path => '../Applio/'


  use_frameworks!

  # Pods for Applio-Example

end
